title: WordPress Hosting Handbook

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - index.md
  - get-involved.md
  - performance.md
  - reliability.md
  - security.md
  - server-environment.md

theme: jekyll-theme-leap-day